#!/bin/bash
# Wrapper script with absolute path
# Generated by SyncMark Installer

BINARY_PATH="/Users/kevin/Projects/syncMackProject/backend_rust/target/release/backend_rust"

if [ -f "$BINARY_PATH" ]; then
    exec "$BINARY_PATH" "$@"
else
    echo "Error: Binary not found at $BINARY_PATH" >> /tmp/syncmark_error.log
    exit 1
fi
